--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElectroGamesYT/RemoteConsole
build-by-default: true
branches:
- main
projects:
  RemoteConsole:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
...
