--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElectroGamesYT/RemoteConsole
build-by-default: true
branches:
- main
projects:
  RemoteConsole:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
