main : Electro\RemoteConsole\RemoteConsole
name: RemoteConsole
version: 1.0.0
api: 3.0.0
Author: Electro

commands:
  console:
    description: Send commands through console
    default: true
    
permissions:
  remoteconsole.password.bypass:
    default: op