main : Electro\RemoteConsole\RemoteConsole
name: RemoteConsole
version: 2.0.3
api: 5.0.0
Author: Electro

commands:
  console:
    description: Send commands through console
    permission: remoteconsole.cmd
    
permissions:
  remoteconsole.password.bypass:
    default: op
  remoteconsole.cmd:
    default: op
    
